services:
  # Development service with hot reload
  blog-dev:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    container_name: gladys-blog-dev
    ports:
      - "8080:1313"
    volumes:
      - ./blog:/blog
    environment:
      - HUGO_ENV=development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1313/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    develop:
      watch:
        - action: sync
          path: ./blog
          target: /blog
        - action: rebuild
          path: ./deploy/Dockerfile

  # Production service with optimized build
  blog-prod:
    build:
      context: .
      dockerfile: deploy/Dockerfile.prod
    container_name: gladys-blog-prod
    ports:
      - "80:80"
    environment:
      - NGINX_WORKER_PROCESSES=auto
      - NGINX_WORKER_CONNECTIONS=1024
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

  # Production service with SSL support (use docker-compose.ssl.yaml for full SSL features)
  blog-prod-ssl:
    build:
      context: .
      dockerfile: deploy/Dockerfile.prod.ssl
    container_name: gladys-blog-prod-ssl
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ssl-certs:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    environment:
      - DOMAIN=${DOMAIN:-localhost}
      - EMAIL=${EMAIL:-admin@localhost}
      - STAGING=${STAGING:-0}
      - NGINX_WORKER_PROCESSES=auto
      - NGINX_WORKER_CONNECTIONS=1024
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f -k https://localhost/health || curl -f http://localhost/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
    profiles:
      - ssl

volumes:
  # SSL certificate volumes
  ssl-certs:
    driver: local
  certbot-webroot:
    driver: local

networks:
  # Custom network for the blog services
  default:
    name: gladys-blog-network
    driver: bridge
