services:
  blog-build:
    build:
      context: .
      dockerfile: deploy/hugo/Dockerfile
    volumes:
      - ./blog/gladys:/blog
    environment:
      - HUGO_ENV=development
    # restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://gladys-blog.local.net:1313"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  gladys-blog:
    build:
      context: .
      dockerfile: deploy/nginx/Dockerfile
    container_name: gladys-blog-c
    restart: unless-stopped
    volumes:
    - ./blog/gladys/public/:/usr/share/nginx/html
    networks:
      gladys-net:
        ipv4_address: 192.168.100.5
networks:
  gladys-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
