baseURL = 'https://example.org/'
languageCode = 'ru'
title = 'Gladys-ai blog'
theme="archie"
copyright = "© 2025 Gladys-ai blog"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourDisqusShortname"

pagination.pagerSize=3 # articles per page

# Build configuration
enableGitInfo = false # Disable Git info to prevent errors when .git is not available
ignoreErrors = ["error-missing-layout"]
ignoreLogs = ['shortcode-x-getremote', 'shortcode-gist']

# Build settings
buildFuture = true
buildExpired = true
buildDrafts = false

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Персональный блог о математике, программировании и науке"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support
	# customCSS = ["css/custom-posts.css"]

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/athul/archie"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/athulcajay/"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/athul/"

# Main menu Items

[[menu.main]]
name = "Главная"
url = "/"
weight = 1

[[menu.main]]
name = "Все посты"
url = "/posts"
weight = 2

[[menu.main]]
name = "О блоге"
url = "/about"
weight = 3

[[menu.main]]
name = "Теги"
url = "/tags"
weight = 4
