baseURL = '/'
languageCode = 'ru'
title = 'Gladys-ai blog'
theme = "archie"
copyright = "© 2025 Gladys-ai blog"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourDisqusShortname"

paginationSize = 10

# Build configuration - simplified for Docker
enableGitInfo = false
enableRobotsTXT = true
canonifyURLs = false
relativeURLs = false

# Error handling
ignoreErrors = ["error-missing-layout", "error-missing-taxonomy"]
ignoreLogs = ["shortcode-x-getremote", "shortcode-gist"]

# Build settings
buildFuture = false
buildExpired = false
buildDrafts = false
removePathAccents = true

[params]
    mode = "auto"
    useCDN = false
    subtitle = "Персональный блог о математике, программировании и науке"
    mathjax = false
    katex = false


# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/athul/archie"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/athulcajay/"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/athul/"

# Main menu Items

[[menu.main]]
name = "Главная"
url = "/"
weight = 1

[[menu.main]]
name = "Все посты"
url = "/posts"
weight = 2

[[menu.main]]
name = "О блоге"
url = "/about"
weight = 3

[[menu.main]]
name = "Теги"
url = "/tags"
weight = 4
